[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
rusqlite = { version = "0.30", features = ["bundled"] }
paho-mqtt = "0.8"
tokio = { version = "1", features = ["full"] }
